version: '2'
services:
  nginx:
    build: docker/nginx
    container_name: symfony_nginx
    volumes:
      - ./symfony:/app
    ports:
      - "8080:80"
    links:
      - php
  php:
    build: docker/php
    container_name: symfony_php
    volumes:
      - ./symfony:/app
    working_dir: /app